export const BUTTON_VARIANT_LINK_KEY = 'link'
export const BUTTON_VARIANT_DEFAULT_KEY = 'default'

export const BUTTON_VARIANTS = {
  LINK: BUTTON_VARIANT_LINK_KEY,
  DEFAULT: BUTTON_VARIANT_DEFAULT_KEY,
} as const

export const BUTTON_DEFAULT_VARIANT = BUTTON_VARIANTS.DEFAULT
export const BUTTON_COMPONENT_VARIANTS_ARRAY = Object.values(BUTTON_VARIANTS)
